### ISSUE TITLE
无法连接到obsidian端口

### ISSUE THREAD

**Issue by chu-shen** [moelody/hexo-link-obsidian#1]
最近也在研究怎么处理obsidian中的wiki链接，感谢制作这款插件👍

使用时遇到两个问题：

**环境：**

- win11
- hexo5.4.0，更新至6.0.0版本同样错误
- NexT主题

### 1.node版本

使用node12时出现此语法错误：`SyntaxError: Unexpected token '.' config?.port`，升级到16后解决

### 2.连接obsidian端口失败

图片能够正确复制到相应位置，但wiki链接直接转换没了，输出的日志如下：

```
>hexo server
INFO  Validating config
INFO  Start processing
INFO  hexo-link-obsidian failed to link obsidian port Cannot read properties of undefined (reading 'adapter')
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
INFO  hexo-link-obsidian Convert && Copy 1 wikiLink files success!
```

**复现：**

在[wiki链接测试文章](https://chushen.xyz/2022/02/10/%E6%B5%8B%E8%AF%95/)中，链接了[另一篇文章](https://chushen.xyz/2022/03/04/%E6%B5%8B%E8%AF%952/)。然后渲染出来发现无此链接。

链接内容如下：

> ## 兼容性
> 
> ![[测试2]]

不知道作者能不能修复下这个问题，感谢

**Comment by moelody** [comment]
@chu-shen 请问使用link-info-server版本号是多少，还有渲染的时候，obsidian必须打开相应的库，这点请确认一下

**Comment by chu-shen** [comment]
@moelody 用的1.0.1，后来看你更新了1.0.2，自己打包试了下也不行

渲染时obsidian打开了对应的库，hexo整个目录也是处于obsidian的根目录下，3333端口正常启用

**Comment by chu-shen** [comment]
@moelody 请问README里说的`abbrlink`指的什么？

使用的[abbrlink插件](https://github.com/rozbo/hexo-abbrlink)吗？这个kv我是写在frontmatter里的

不过好像没获取到这个值，都转到404去了`http://localhost:4000/404#测试2`

**Comment by moelody** [comment]
> @moelody 请问README里说的`abbrlink`指的什么？
> 
> 使用的[abbrlink插件](https://github.com/rozbo/hexo-abbrlink)吗？这个kv我是写在frontmatter里的
> 
> 不过好像没获取到这个值，都转到404去了`http://localhost:4000/404#测试2`

我更新了版本和readme，确实必须配合abbrlink插件使用，之前只有我一个人再用也没在意这个，你试试

**Comment by chu-shen** [comment]
@moelody 👍链接生成成功

不过a标签这块显示有点问题`<a href="/posts/74231343#%E6%B5%8B%E8%AF%952%7CTEST" data-pjax-state=""></a>`

提了个pr修复这个问题

**Comment by moelody** [comment]
@chu-shen 已更新👌
