### ISSUE TITLE
关于网络图片的问题

### ISSUE THREAD

**Issue by uuanqin** [moelody/hexo-link-obsidian#3]
该插件对网络图片似乎处理得不是很好，如`![](https://typora-1301301520.file.myqcloud.com/img/image-20230511165810324.png)`
Hexo渲染后显示字符串为`null`。

是否可以关闭该插件对网络图片（或形如`![img](imglink.png)`）的处理，因为博客里所有图片均上传图床。

我目前的做法是更改[index.js文件中获取图片链接的正则表达式](https://github.com/moelody/hexo-link-obsidian/blob/main/index.js#L28)

目前效果不错，不知会不会产生什么bug。

Hexo版本：5.4.2
Windows：10
主题：Butterfly 4.8.1

**Comment by moelody** [comment]
可能会影响嵌入视频的转换，我已对网络图片进行了正则判断，可以更新到最新版本

**Comment by uuanqin** [comment]
作者你好，感谢你的回复，新版本确实解决了部分网络图片显示的问题。但是现在有新的问题出现，仍存在个别图片显示为null。

复现的例子：

```markdown
![image-20230427194929460](https://typora-1301301520.file.myqcloud.com/img/image-20230427194929460.png)

![image-20230427194929460](https://typora-1301301520.file.myqcloud.com/img/image-20230427194929460.png)

![image-20230427194929460](https://typora-1301301520.file.myqcloud.com/img/image-20230427194929460.png)

![image-20230427194929460](https://typora-1301301520.file.myqcloud.com/img/image-20230427194929460.png)
```

渲染结果为：
![image](https://github.com/moelody/hexo-link-obsidian/assets/61202052/4a5b92be-c893-4491-8eff-406233439431)

**Comment by moelody** [comment]
> 作者你好，感谢你的回复，新版本确实解决了部分网络图片显示的问题。但是现在有新的问题出现，仍存在个别图片显示为null。
> 
> 复现的例子：
> 
> ```gfm
> ![image-20230427194929460](https://typora-1301301520.file.myqcloud.com/img/image-20230427194929460.png)
> 
> ![image-20230427194929460](https://typora-1301301520.file.myqcloud.com/img/image-20230427194929460.png)
> 
> ![image-20230427194929460](https://typora-1301301520.file.myqcloud.com/img/image-20230427194929460.png)
> 
> ![image-20230427194929460](https://typora-1301301520.file.myqcloud.com/img/image-20230427194929460.png)
> ```
> 
> 渲染结果为： ![image](https://user-images.githubusercontent.com/61202052/243902086-4a5b92be-c893-4491-8eff-406233439431.png)

确实有问题，我排查了下是正则的test方法出了问题，使用全局模式这个方法的index会反复横跳，查缺补漏了😅
已修正发布新版本
