### ISSUE TITLE
关于生成的链接加html的建议等其他问题

### ISSUE THREAD

**Issue by uuanqin** [moelody/hexo-link-obsidian#4]
插件非常棒！但是也有一点点小问题。

1. 当博客**发布到互联网**后，链接的地址指向404页面，这是因为生成的是这样的链接：

`https://www.uuanqin.top/p/28a4bfe2` 点击后会指向404页面。

但是加上.html后就没问题了，如：`https://www.uuanqin.top/p/28a4bfe2.html`

但是博客在本地调试的时候即使少了.html也没有上述问题，我也不懂为啥......还是希望加上个.html吧

2. 少部分双向链接没有被渲染。这些双向链接在Obsidian工作正常，但是在Hexo上不起作用（不管是本地调试还是发布到互联网）

比如这个链接：`[[https的配置]]` 。目前只找到这一个，其他均正常。

参考页面：https://www.uuanqin.top/p/e4b7f93a.html

（我不太懂咋复现这个问题，作者需要啥信息告诉我）

**Comment by moelody** [comment]
1. ![image](https://github.com/moelody/hexo-link-obsidian/assets/30750380/e49ef8fc-0be0-4086-a636-fe6a42f739e9)
应该是你配置填写不正确，permalink填写参考，该插件不应该改变最后生成链接，否则会和其他插件冲突。
2. https 开头被识别成网络文件跳过了, 目前已改变识别逻辑不再跳过http开头的wiki文件

**Comment by uuanqin** [comment]
OK！第一个问题解决了，确实是我的配置错了

但好像npm拉取不到v1.1.6版本......是不是得再等会
