### ISSUE TITLE
关于生成的链接问题

### ISSUE THREAD

**Issue by uuanqin** [moelody/hexo-link-obsidian#5]
博主你好！

在我的_config.yml中，永久链接格式为
```yaml
permalink: p/:abbrlink/
```

![image](https://github.com/moelody/hexo-link-obsidian/assets/61202052/1ada18f9-00c5-4433-9059-660226d7291c)

但是插件转化后的地址后面没有斜杠（即使是`permalink: p/:abbrlink//`）：

![image](https://github.com/moelody/hexo-link-obsidian/assets/61202052/1b5b6ef7-e7f4-4882-9404-990b4e912f7b)

导致的问题是在部署到服务器的时候，不同的链接实际跳转的地址不同：
| 鼠标悬浮于链接时显示  |  实际跳转到的网页 |
|  ----- | ----- |
| https://www.uuanqin.top/p/f06d4de6 | 我的主机IP/p/f06d4de6/  |
| https://www.uuanqin.top/p/f06d4de6/  |  https://www.uuanqin.top/p/f06d4de6/ (理想状况) |

复现：这篇文章 https://www.uuanqin.top/p/18bbd410/ 的最后一个链接

看看能不能修复下~

> 另外，插件的1.1.6版本现在还是没能下载下来。重装也不行

**Comment by moelody** [comment]
![image](https://github.com/moelody/hexo-link-obsidian/assets/30750380/1bad72e0-d179-4e02-b9b3-08ebc4652776)
还真是奇怪的问题，我已经改成默认加上斜杆了，更新到1.1.7吧

**Comment by uuanqin** [comment]
我卸了重装后还是1.1.5
```sh
npm i hexo-link-obsidian -s
```
这是为啥捏，Github上保持1.1.6😥

**Comment by moelody** [comment]
> 我卸了重装后还是1.1.5
> 
> ```shell
> npm i hexo-link-obsidian -s
> ```
> 
> 这是为啥捏，Github上保持1.1.6😥

这和github无关，如果你有lock.json的文件请删掉后重装

**Comment by uuanqin** [comment]
成功了！
更新一下npm就行。
```sh
npm install -g npm
```
